vich_uploader:
    db_driver: orm

    mappings:
        blog_image:
            uri_prefix: '%app.path.blog_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.blog_image%'
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true