#index:
#    path: /
#    controller: App\Controller\DefaultController::index
<<<<<<< Updated upstream
=======
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
>>>>>>> Stashed changes
